[build]
  command = "npm run build"
  publish = "dist"

# Handle JSX files properly
[[headers]]
  for = "/*.js"
  [headers.values]
    Content-Type = "application/javascript"

[[headers]]
  for = "/src/*.jsx"
  [headers.values]
    Content-Type = "application/javascript"

# SPA fallback
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200