[build]
  command = "npm run build"
  publish = "dist"

# Fix MIME type for JS files
[[headers]]
  for = "/*.js"
  [headers.values]
    Content-Type = "application/javascript"

[[headers]]
  for = "/*.jsx"
  [headers.values]
    Content-Type = "application/javascript"

# SPA fallback
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200